In [105]:
import numpy as np

import random


In [133]:
random.seed(1)

X = [[2,22,12,-43],
    [-3,12,-15,43],
    [10,-33,14,45]]


class HiddenLayer():
    def __init__(self,n_inputs,n_neurons):
        
        self.weights = np.random.randn(n_inputs,n_neurons)
        
        #or
        #self.weights = np.random.randn(n_neurons,n_inputs).T
        
        self.biases = np.zeros((1,n_neurons)) +1.2
        
    def Forward(self,inputs):
        self.output = np.dot(inputs , self.weights) + self.biases

        
class Activate_neurons():
    
    def activate_ReLu(self,inputs):
        self.output = np.maximum(0,inputs)

In [134]:
layer1 = HiddenLayer(4,5)

In [135]:
layer1.Forward(X)

In [136]:
layer1.output

array([[ 52.98715251,   5.8261633 ,  45.62975131, -49.12326763,
         23.98892182],
       [ -7.99019761,  54.50088581, -29.32093515,   7.1294403 ,
          7.24438025],
       [-70.43134963, -45.29304467, -65.93300312, 104.23813394,
        -32.67538957]])

In [137]:
activate = Activate_neurons()
activate.activate_ReLu(layer1.output)

In [138]:
activate.output

array([[ 52.98715251,   5.8261633 ,  45.62975131,   0.        ,
         23.98892182],
       [  0.        ,  54.50088581,   0.        ,   7.1294403 ,
          7.24438025],
       [  0.        ,   0.        ,   0.        , 104.23813394,
          0.        ]])

In [139]:
layer2 = HiddenLayer(5, 2)
layer2.Forward(activate.output)

In [140]:
activate2 = Activate_neurons()
activate2.activate_ReLu(layer2.output)

In [141]:
activate2.output

array([[26.11313657, 22.837741  ],
       [50.7941653 , 51.45146618],
       [ 9.31192915, 65.65880457]])